name: "ADLS connectivity test"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      storage:
        description: 'Enter the storage account name' 
        required: true
        default: 'blob17'
        type: string
      pe:
        description: 'Is this a private endpoint ?' 
        required: true
        default: true
        type: boolean


jobs:
  test-public-endpoint:
    runs-on: ubuntu-latest

    if: ${{ inputs.pe  == false }}
    steps:
      - name: Launch a connectivity test from gha private runners towards the storage account blob port 443
        id: test1
        shell: pwsh
        run: |
          $connection = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.blob.core.windows.net","443")
          if ($connection.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }
        #if: ${{ failure() ||  success() }}
      - name: Launch a connectivity test from gha private runners towards the storage account dfs port 443 
        id: test2
        if: ${{ failure() ||  success() }}
        shell: pwsh
        run: |
          $connection2 = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.dfs.core.windows.net","443")
          if ($connection2.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }

  test-private-endpoint:
    runs-on: ubuntu-latest

    if: ${{ inputs.pe  == true }}
    steps:
      - name: Launch a connectivity test from gha private runners towards the storage account blob port 443
        id: test1
        shell: pwsh
        run: |
          $env:no_proxy = $env:no_proxy + '.local,localhost,127.0.0.1,' + 'dfs.core.windows.net,blob.core.windows.net'
          $connection = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.blob.core.windows.net","443")
          if ($connection.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }
        #if: ${{ failure() ||  success() }}
      - name: Launch a connectivity test from gha private runners towards the storage account dfs port 443 
        id: test2
        if: ${{ failure() ||  success() }}
        shell: pwsh
        run: |
          $env:no_proxy = $env:no_proxy + '.local,localhost,127.0.0.1,' + 'dfs.core.windows.net,blob.core.windows.net'
          $connection2 = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.dfs.core.windows.net","443")
          if ($connection2.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }