name: "ADLS connectivity test"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      storage:
        description: 'Enter the storage account name' 
        required: true
        default: 'blob17'
        type: string


jobs:
  test-tcp-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Launch a connectivity test from gha private runners towards the storage account blob port 443
        continue-on-error: true
        shell: pwsh
        run: |
          $connection = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.blob.core.windows.net","448")
          if ($connection.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }
      - name: Launch a connectivity test from gha private runners towards the storage account dfs port 443 
        shell: pwsh
        continue-on-error: true
        run: |
          $connection2 = New-Object System.Net.Sockets.TcpClient("${{ inputs.storage }}.dfs.core.windows.net","443")
          if ($connection2.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }
