name: "ADLS connectivity test"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      decision:
        description: 'Enter the storage account name' 
        required: true
        default: 'blob17'
        type: choice
        options:
          - blob17
          - tst

jobs:
  test-tcp-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Launch a connectivity test from gha private runners towards the storage account ports 443
        shell: pwsh
        run: |
          Test-NetConnection -ComputerName ${{ inputs.storage }}.blob.core.windows.net -Port 443
          Test-NetConnection -ComputerName ${{ inputs.storage }}.dfs.core.windows.net -Port 443