name: "delete container"
      
on:
  
  workflow_dispatch:
    inputs:
      decision:
        description: 'Please confirm in which environment you wish to delete ' 
        required: true
        default: 'which environment ?'
        type: choice
        options:
          - which environment ?
          - dev
          - tst
          - prd

jobs:
  delete-container:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if:  ${{ inputs.decision }} 
    environment:
      name: ${{ inputs.decision }}
    steps:
     
      - uses: actions/checkout@v4
      
      # Login via Fed id service principal linked to my repo and my environment
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Delete container inside storage account
        shell: pwsh
        run: |
          az storage container delete --auth-mode login --account-name underwritingweu --name test
          az storage container delete --auth-mode login --account-name underwritingweu --name test2