name: "Private endpoint connectivity test"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      endpointurl:
        description: 'Enter the endpoint fqdn:' 
        required: true
        default: 'fqdn'
        type: string
      endpointport:
        description: 'Port:' 
        required: true
        default: '443'
        type: string


jobs:
  test-tcp-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Launch a connectivity test from gha private runners towards the storage account blob port 443
        id: test1
        continue-on-error: true
        shell: pwsh
        run: |
          $connection = New-Object System.Net.Sockets.TcpClient("${{ inputs.endpointurl }}","${{ inputs.endpointport }}")
          if ($connection.Connected) {
            Write-Host "Success" 
          } else { 
            Write-Host "Failed" 
          }

      - name: Check on failures
        if: job.steps.test1.outcome != 'success' 
        run: exit 1
