name: "List file from different repo"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Do you want to deploy to DEV ? Please confirm the environment' 
        required: true
        default: 'dev'
        type: choice
        options:
          - which environment ?
          - dev
      granularity:
        description: 'deploy security groups at storage account or container level?' 
        required: true
        default: 'storage account'
        type: choice
        options:
          - storage account
          - container

jobs:

  deploy-with-security-groups-at-storage-account-level:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ inputs.environment }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout local repo
        uses: actions/checkout@v3
      
      - name: Checkout DAnDE repo
        uses: actions/checkout@v4
        with:
          repository: blippu/githubactions
          ref: main

      # Login via Fed id service principal linked to my repo and my environment
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Read container from local repo
        id: package
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: ./dev/container.txt


      - name: Run script
        run: |
          ls -al ./dev
          cat ./dev/container.txt
