name: "List env"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables
        run: echo ${{ vars.tenant  }}
      - name: Print the environment variables
        run: echo ${{ env.dev.vars.tenant  }}
      - name: Print the environment variables
        run: env