name: "CAll List env"
            
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:

jobs:


  call_workflow_storage_account_level:


    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/listenv.yml@feature/DDM-1012
