name: "workflow"

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  trigger_workflow:
      runs-on: ubuntu-latest
      steps:
        -name: "Trigger child workflow"
         uses: convictional/trigger-workflow-and-wait
         with:
           owner: blippu
           repo: githubactions
           workflow_file_name: dev.yml
