name: "workflow"

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  trigger_workflow:
    - uses: blippu/githubactions/.github/workflows/dev.yml@v0.1
      with:
        config_file: dev/container.txt