name: "DEV Call dande workflow"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      decision:
        description: 'Do you want to deploy to DEV ? Please confirm the environment' 
        required: true
        default: 'which environment ?'
        type: choice
        options:
          - which environment ?
          - dev
      granularity:
        description: 'deploy security groups at storage account or container level?' 
        required: true
        default: 'storage account'
        type: choice
        options:
          - storage account
          - container
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.decision }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.decision }} 

  call_workflow_storage_account_level:
    if: ${{ inputs.decision  == 'dev'}}
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/dev-v2.yml@main
    with:
      config-file: dev/container.txt
      environment: ${{ inputs.decision }}
      granularity: ${{ inputs.granularity }}