name: "workflow"

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  trigger_workflow:
      runs-on: ubuntu-latest
      
      steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: blippu
          repo: githubactions
          workflow_file_name: dev.yml
          github_token: ${{ secrets.PAT }}
