name: "workflow"

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  trigger_workflow:
      runs-on: ubuntu-latest
      
      steps:
      - uses: blippu/githubactions/.github/workflows/dev.yml
        with:
          config_file: dev/container.txt