name: "TST Call dande workflow"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
  
jobs:
  call_workflow:
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/dev-v2.yml@main
    with:
      config-file: tst/container.txt