name: "DEV Call dande workflow"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      decision:
        description: 'Are you sure you want to deploy to DEV ?'
        required: true
        default: 'not really'
        type: choice
        options:
          - not really
          - yes I am sure
          - maybe
  
jobs:


  call_workflow:
    if: ${{ inputs.decision }} == "yes I am sure"
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/dev-v2.yml@main
    with:
      config-file: dev/container.txt