name: "workflow"

permissions:
      id-token: write
      contents: read
      
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

  
jobs:
  call_workflow:
    uses: blippu/githubactions/.github/workflows/dev.yml@v0.1
    with:
      config_file: dev/container.txt