name: "DEV Call dande workflow"
      
on:
#  push:
#    branches:
#      - main
  
  workflow_dispatch:
    inputs:
      decision:
        description: 'Are you sure you want to deploy to DEV ? please confirm the environment' 
        required: true
        default: 'not really'
        type: choice
        options:
          - not really
          - dev

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.decision }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.decision }} 

  call_workflow:
    if: ${{ inputs.decision }} == 'dev'
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/dev-v2.yml@main
    with:
      config-file: dev/container.txt
      environment: ${{ inputs.decision }}