name: "Call dande workflow"
      
on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  call_workflow:
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: ./.github/workflows/dev-v2.yml
    with:
      config-file: ./dev/container.txt