name: "Call dande workflow"
      
on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:
  call_workflow:
    secrets: inherit
    permissions:
        id-token: write
        contents: read
    uses: blippu/githubactions/.github/workflows/dev-v2.yml@v0.1
    with:
      config-file: dev/container.txt